import { EdTechEvent } from './types';

export const events: EdTechEvent[] = [
    {
        id: 1,
        name: "CIC Presidents Institute 2026",
        date: "2026-01-04",
        location: "Orlando, Florida, EE.UU.",
        region: "Norteamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "4 al 7 de Enero de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 28.5383,
        lng: -81.3792,
        website: "https://cic.edu/event/2026-presidents-institute/"
    },
    {
        id: 2,
        name: "FETC",
        date: "2026-01-11",
        location: "Orlando, Florida, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "11 al 14 de Enero de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 28.5383,
        lng: -81.3792,
        website: "https://www.fetc.org/"
    },
    {
        id: 3,
        name: "Global Education Forum - Madrid 2026",
        date: "2026-01-15",
        location: "Madrid, España",
        region: "Europa",
        type: "Educación superior / internacionalización",
        relevance: "Media",
        notes: "15 al 18 de Enero de 2026 - Empresas: Universidad Siglo 21, Cerem",
        lat: 40.4168,
        lng: -3.7038,
        website: "https://thecgdl.org/ygf2026/"
    },
    {
        id: 4,
        name: "ISTE+ASCD Instructional Leaders' Summit 2026",
        date: "2026-01-16",
        location: "San Diego, California, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "16 al 19 de Enero de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 32.7157,
        lng: -117.1611,
        website: "https://event.iste-ascd.org/ILS26/"
    },
    {
        id: 5,
        name: "Get Your Teach On (GYTO) Fest",
        date: "2026-01-17",
        location: "Las Vegas, Nevada, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "17 al 19 de Enero de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 36.1699,
        lng: -115.1398,
        website: "https://events.getyourteachon.com/vegas2026?ref=gytosite"
    },
    {
        id: 6,
        name: "AAC&U Annual Meeting 2026",
        date: "2026-01-21",
        location: "Washington D.C., EE.UU.",
        region: "Norteamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "21 al 23 de Enero de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 38.9072,
        lng: -77.0369,
        website: "https://www.aacu.org/events"
    },
    {
        id: 7,
        name: "IFE EdTech Summit",
        date: "2026-01-27",
        location: "Monterrey, México",
        region: "Latinoamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "27 al 29 de Enero de 2026 - Empresas: Capabilia, Benchlab, Bitlogic, Siglo 21, Social Learning, R'Evolution",
        lat: 25.6866,
        lng: -100.3161,
        website: "https://startupslatam.com/ife-edtech-summit-2026-monterrey-sera-el-epicentro-de-la-innovacion-educativa-en-america-latina/"
    },
    {
        id: 8,
        name: "TCEA Convention",
        date: "2026-01-31",
        location: "San Antonio, Texas, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "31 de Enero al 4 de Febrero de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 29.4241,
        lng: -98.4936,
        website: "https://convention.tcea.org/about/faqs/"
    },
    {
        id: 9,
        name: "AI K12 Deeper Learning Summit",
        date: "2026-02-03",
        location: "Hershey, PA, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "3 de Febrero de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 40.2848,
        lng: -76.6502,
        website: "https://www.peteandc.org/2026/ThirdSummit.cfm"
    },
    {
        id: 10,
        name: "World Education Summit",
        date: "2026-02-04",
        location: "Dubai, EAU",
        region: "Resto del Mundo",
        type: "Educación superior / internacionalización",
        relevance: "Media",
        notes: "4 y 5 de Febrero de 2026 - Empresas: Universidad Siglo 21, Cerem",
        lat: 25.2048,
        lng: 55.2708,
        website: "https://educationsummit.com/"
    },
    {
        id: 11,
        name: "AASA National Conference on Education",
        date: "2026-02-12",
        location: "Nashville, Tennessee, EE.UU.",
        region: "Norteamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "12 al 14 de Febrero de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 36.1627,
        lng: -86.7816,
        website: "https://www.aasa.org/professional-learning/national-conference-on-education"
    },
    {
        id: 12,
        name: "Digital Learning Annual Conference",
        date: "2026-02-18",
        location: "Sacramento, California, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "18 al 20 de Febrero de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 38.5816,
        lng: -121.4944,
        website: "https://conference.deelac.com/future-dlac-dates"
    },
    {
        id: 13,
        name: "Digital Credentials Summit",
        date: "2026-02-18",
        location: "Filadelfia, Pensilvania, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "18 al 20 de Febrero de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 39.9526,
        lng: -75.1652,
        website: "https://www.cvent.com/c/abstracts/4eacc00f-fabc-4fae-8a73-72d26b867f39"
    },
    {
        id: 14,
        name: "ACE Experience 2026",
        date: "2026-02-25",
        location: "Washington D.C., EE.UU.",
        region: "Norteamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "25 al 28 de Febrero de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 38.9072,
        lng: -77.0369,
        website: "https://web.cvent.com/event/7d76e475-73c0-4b97-b034-7cf56b1dd7b9/summary"
    },
    {
        id: 15,
        name: "Beyond School Hours (BSH)",
        date: "2026-03-01",
        location: "Orlando, Florida, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "1 al 4 de Marzo de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 28.5383,
        lng: -81.3792,
        website: "https://beyondschoolhours.org/"
    },
    {
        id: 16,
        name: "OLC Innovate 2026",
        date: "2026-03-03",
        location: "Virtual",
        region: "Por confirmar",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "3 al 5 de Marzo de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 0,
        lng: 0,
        website: "https://onlinelearningconsortium.org/conferences/"
    },
    {
        id: 17,
        name: "SXSW EDU",
        date: "2026-03-09",
        location: "Austin, Texas, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "9 al 12 de Marzo de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 30.2672,
        lng: -97.7431,
        website: "https://sxswedu.com/"
    },
    {
        id: 18,
        name: "Edutic Ontour",
        date: "2026-03-18",
        location: "Ciudad de México, México",
        region: "Latinoamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "18 de Marzo de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 19.4326,
        lng: -99.1332,
        website: "https://conference.edutic.org/mx/cdmx2026/"
    },
    {
        id: 19,
        name: "Spring CUE 2026",
        date: "2026-03-19",
        location: "Palm Springs, California, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "19 al 21 de Marzo de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 33.8303,
        lng: -116.5453,
        website: "https://cadrek12.org/events/2026/03/19/computer-using-educators-spring-cue-2026-national-conference-palm-springs-ca"
    },
    {
        id: 20,
        name: "HolonIQ Global Skills Week",
        date: "2026-03-24",
        location: "Washington D.C., EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "24 al 26 de Marzo de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 38.9072,
        lng: -77.0369,
        website: "https://portal.qshesummits.com/event/global-skills-week/home"
    },
    {
        id: 21,
        name: "FORUMEDUCA",
        date: "2026-03-17",
        location: "España",
        region: "Europa",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "17 y 18, 18 y 19 de Marzo 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 0,
        lng: 0,
        website: "https://www.forumeduca.com/"
    },
    {
        id: 22,
        name: "Graduate Enrollment Management Summit 2026",
        date: "2026-04-08",
        location: "Baltimore, Maryland, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "8 al 11 de Abril de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 39.2904,
        lng: -76.6122,
        website: "https://nagap.memberclicks.net/2025-GEM-Summit"
    },
    {
        id: 23,
        name: "ASU+GSV Summit",
        date: "2026-04-12",
        location: "San Diego, California, EE.UU.",
        region: "Norteamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "12 al 15 de Abril de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 32.7157,
        lng: -117.1611,
        website: "https://asugsvsummit.com/"
    },
    {
        id: 24,
        name: "CoSN 2026",
        date: "2026-04-13",
        location: "Chicago, Illinois, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "13 al 15 de Abril de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 41.8781,
        lng: -87.6298,
        website: "https://serve.uncg.edu/event/cosn-conference-2026/"
    },
    {
        id: 25,
        name: "UPCEA 2026 Annual Conference",
        date: "2026-04-15",
        location: "Nueva Orleans, Louisiana, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "15 al 17 de Abril de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 29.9511,
        lng: -90.0715,
        website: "https://conferences.upcea.edu/annual2026/"
    },
    {
        id: 26,
        name: "Etech Evolving Education - Conexión Educativa",
        date: "2026-04-23",
        location: "Puebla, México",
        region: "Latinoamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "23 de abril de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 19.0414,
        lng: -98.2063,
        website: "https://www.etechevolvingeducation.com/"
    },
    {
        id: 27,
        name: "Bett Brasil",
        date: "2026-05-05",
        location: "São Paulo, Brasil",
        region: "Latinoamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "5 al 8 de Mayo de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: -23.5505,
        lng: -46.6333,
        website: "https://brasil.bettshow.com/credenciamento"
    },
    {
        id: 28,
        name: "THE Latin America Universities Summit",
        date: "2026-05-12",
        location: "Barranquilla, Colombia",
        region: "Latinoamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "12 al 14 de Mayo de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 10.9685,
        lng: -74.7813,
        website: "https://www.timeshighered-events.com/latin-america-universities-summit-2026"
    },
    {
        id: 29,
        name: "ATD 2026 International Conference & Expo",
        date: "2026-05-17",
        location: "Los Ángeles, California, EE.UU.",
        region: "Norteamérica",
        type: "Corporate learning / L&D",
        relevance: "Media",
        notes: "17 al 20 de Mayo de 2026 - Empresas: Capabilia, Social Learning",
        lat: 34.0522,
        lng: -118.2437,
        website: "https://www.nferias.com/atd-conference-exposition/"
    },
    {
        id: 30,
        name: "Inn.kind FIEd 2026",
        date: "2026-05-19",
        location: "Ciudad de Panamá, Panamá",
        region: "Latinoamérica",
        type: "Tecnología educativa / EdTech",
        relevance: "Media",
        notes: "19 al 21 mayo - Empresas: Klarway",
        lat: 8.9824,
        lng: -79.5199,
        website: "https://innkind.com/"
    },
    {
        id: 31,
        name: "RECLA",
        date: "2026-05-27",
        location: "Salta, Argentina",
        region: "Latinoamérica",
        type: "Tecnología educativa / EdTech",
        relevance: "Media",
        notes: "27, 28 y 29 de mayo - Empresas: Klarway",
        lat: -24.7821,
        lng: -65.4232,
        website: "https://recla.org/encuentro-regional/"
    },
    {
        id: 32,
        name: "EDUCAUSE Cybersecurity & Privacy",
        date: "2026-05-2026",
        location: "Por confirmar",
        region: "Por confirmar",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "Por confirmar (Estimado: Mayo 2026) - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 0,
        lng: 0,
        website: "https://www.educause.edu/focus-areas-and-initiatives/policy-and-security/cybersecurity-program/resources"
    },
    {
        id: 33,
        name: "Future Talent Council Global Summit 2026",
        date: "2026-06-16",
        location: "Stocolmo, Suecia",
        region: "Europa",
        type: "Educación / innovación (general)",
        relevance: "Media",
        notes: "16 y 17 junio de 2026 - Empresas: Siglo 21",
        lat: 59.3293,
        lng: 18.0686,
        website: "https://www.futuretalentsummit.org/"
    },
    {
        id: 34,
        name: "ISTELive 25 + ASCD Annual",
        date: "2026-06-28",
        location: "Orlando, Florida, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "28 de Junio al 1 de Julio de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 28.5383,
        lng: -81.3792,
        website: "https://conference.iste.org/"
    },
    {
        id: 35,
        name: "Model Schools Conference 2026",
        date: "2026-06-28",
        location: "Orlando, Florida, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "28 de Junio al 1 de Julio de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 28.5383,
        lng: -81.3792,
        website: "https://www.hmhco.com/model-schools-conference"
    },
    {
        id: 36,
        name: "ISTELive 26 + ASCD Annual 26",
        date: "2026-06-28",
        location: "Orlando, Florida, EE.UU.",
        region: "Norteamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "28 de Junio al 1 de Julio de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 28.5383,
        lng: -81.3792,
        website: "https://conference.iste.org/"
    },
    {
        id: 37,
        name: "InstructureCon 2026",
        date: "2026-07-21",
        location: "Louisville, Kentucky, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "21 al 23 de Julio de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 38.2527,
        lng: -85.7585,
        website: "https://www.instructure.com/events/instructurecon/faqs"
    },
    {
        id: 38,
        name: "Innova Educa",
        date: "2026-08-20",
        location: "Buenos Aires, Argentina",
        region: "Latinoamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "20 y 21 de Agosto - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: -34.6037,
        lng: -58.3816,
        website: "https://21.edu.ar/la-universidad/presencia-regional/innova-educa-21"
    },
    {
        id: 39,
        name: "Edutechnia",
        date: "2026-08-26",
        location: "Bogotá, Colombia",
        region: "Latinoamérica",
        type: "Tecnología educativa / K-12 / EdTech",
        relevance: "Alta",
        notes: "26 al 28 de Agosto de 2026 - Empresas: Capabilia, Benchlab, Bitlogic",
        lat: 4.711,
        lng: -74.0721,
        website: "https://www.edutechnia.com/pdf/Presentacion-Edutechnia-2026.pdf"
    },
    {
        id: 40,
        name: "EdTech Conference Buenos Aires",
        date: "2026-09-02",
        location: "Buenos Aires, Argentina",
        region: "Latinoamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "2 de septiembre 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: -34.6037,
        lng: -58.3816,
        website: "https://www.edtechconference.com.ar/"
    },
    {
        id: 41,
        name: "HolonIQ Back to School Summit",
        date: "2026-09-08",
        location: "Nueva York, NY, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "8 al 10 de Septiembre de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 40.7128,
        lng: -74.006,
        website: "https://insights.qs.com/qs-conferences-2025-2026-landing-page"
    },
    {
        id: 42,
        name: "HolonIQ Impact Week",
        date: "2026-09-08",
        location: "Nueva York / Singapur",
        region: "Resto del Mundo",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "8 al 12 de Septiembre de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 40.7128,
        lng: -74.006,
        website: "https://impactweek.com/"
    },
    {
        id: 43,
        name: "Inbound HubSpot",
        date: "2026-09-16",
        location: "Boston, Massachusetts, EE.UU.",
        region: "Norteamérica",
        type: "Marketing y tecnología comercial",
        relevance: "Media",
        notes: "16 al 18 de Septiembre de 2026 - Empresas: Capabilia, Benchlab, Klarway",
        lat: 42.3601,
        lng: -71.0589,
        website: "https://www.cmswire.com/events/conference/hubspot-inbound-boston-2026/"
    },
    {
        id: 44,
        name: "EDUCAUSE Annual Conference 2026",
        date: "2026-09-29",
        location: "Denver, Colorado, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "29 de Septiembre al 2 de Octubre de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 39.7392,
        lng: -104.9903,
        website: "https://events.educause.edu/annual-conference/2026"
    },
    {
        id: 45,
        name: "QS Higher Ed Summit: Americas 2026",
        date: "2026-10-01",
        location: "Guadalajara, México",
        region: "Latinoamérica",
        type: "Educación superior / internacionalización",
        relevance: "Media",
        notes: "1 y 2 de Octubre de 2026 - Empresas: Universidad Siglo 21, Cerem",
        lat: 20.6597,
        lng: -103.3496,
        website: "https://www.qs.com/conferences/americas"
    },
    {
        id: 46,
        name: "NACAC Conference 2026",
        date: "2026-10-08",
        location: "Minneapolis, Minnesota, EE.UU.",
        region: "Norteamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "8 al 10 de Octubre de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 44.9778,
        lng: -93.265,
        website: "https://www.tacac.org/nacac"
    },
    {
        id: 47,
        name: "EdTech Week",
        date: "2026-10-12",
        location: "Nueva York, NY, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "12 al 16 de Octubre de 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 40.7128,
        lng: -74.006,
        website: "https://www.edtechweek.com/"
    },
    {
        id: 48,
        name: "CAEI Congreso de las Américas sobre Educación Internacional",
        date: "2026-10-15",
        location: "San José, Costa Rica",
        region: "Latinoamérica",
        type: "Educación superior / internacionalización",
        relevance: "Media",
        notes: "15, 16 y 17 de octubre - Bianual - Empresas: Universidad Siglo 21, Cerem",
        lat: 9.9281,
        lng: -84.0907,
        website: "https://oui-iohe.org/es/caei-caie/"
    },
    {
        id: 49,
        name: "Learning Leaders Conference",
        date: "2026-11-02",
        location: "Las Vegas, Nevada, EE.UU.",
        region: "Norteamérica",
        type: "Corporate learning / L&D",
        relevance: "Media",
        notes: "2 y 3 de Noviembre de 2026 - Empresas: Capabilia, Social Learning",
        lat: 36.1699,
        lng: -115.1398,
        website: "https://www.learningguild.com/event/learning-leadership-conference"
    },
    {
        id: 50,
        name: "Realcup",
        date: "2026-11-11",
        location: "Ecuador",
        region: "Latinoamérica",
        type: "Tecnología educativa / EdTech",
        relevance: "Media",
        notes: "11 al 13 de noviembre - Empresas: Klarway",
        lat: 0,
        lng: 0,
        website: "https://realcup.org/"
    },
    {
        id: 51,
        name: "DevLearn 2025 Conference & Expo",
        date: "2026-11-04",
        location: "Las Vegas, Nevada, EE.UU.",
        region: "Norteamérica",
        type: "Educación / innovación (general)",
        relevance: "Muy Alta",
        notes: "4 al 6 de Noviembre 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 36.1699,
        lng: -115.1398,
        website: "https://www.learningguild.com/event/devlearn-2025-conference-expo"
    },
    {
        id: 52,
        name: "OLC Accelerate 2026",
        date: "2026-11-16",
        location: "Orlando, Florida, EE.UU.",
        region: "Norteamérica",
        type: "Educación digital / innovación educativa",
        relevance: "Muy Alta",
        notes: "16 al 19 de Noviembre 2026 - Empresas: Universidad Siglo 21, Cerem, Capabilia, Benchlab",
        lat: 28.5383,
        lng: -81.3792,
        website: "https://onlinelearningconsortium.org/conferences/olc-accelerate2026/"
    }
];
