
import { EdTechEvent } from './types';

export const events: EdTechEvent[] = [
    { 
        id: 1, 
        name: "ISTELive 25 + ASCD Annual", 
        date: "2026-06-28", 
        location: "Orlando, Florida, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Muy Alta", 
        notes: "Prioridad A. Marketing Capabilia y Benchlab. Confirmado como ISTELive 26.", 
        lat: 28.5383, 
        lng: -81.3792, 
        website: "https://conference.iste.org/" 
    },
    { 
        id: 2, 
        name: "ASU+GSV Summit", 
        date: "2026-04-12", 
        location: "San Diego, California, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Muy Alta", 
        notes: "Prioridad A. Estrategia y Corporate Brand. Detección de oportunidades y networking.", 
        lat: 32.7157, 
        lng: -117.1611, 
        website: "https://asugsvsummit.com/" 
    },
    { 
        id: 3, 
        name: "EdTech Week", 
        date: "2026-10-12", 
        location: "Nueva York, NY, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Reforzar liderazgo en educación online.", 
        lat: 40.7128, 
        lng: -74.0060, 
        website: "https://www.edtechweek.com/" 
    },
    { 
        id: 4, 
        name: "EDUCAUSE Annual 2025", 
        date: "2026-09-29", 
        location: "Denver, Colorado, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Alianzas institucionales.", 
        lat: 39.7392, 
        lng: -104.9903, 
        website: "https://events.educause.edu/annual-conference/2026" 
    },
    { 
        id: 5, 
        name: "HolonIQ Back to School Summit", 
        date: "2026-09-08", 
        location: "Nueva York, NY, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Networking de alto nivel.", 
        lat: 40.7128, 
        lng: -74.0060, 
        website: "https://insights.qs.com/qs-conferences-2025-2026-landing-page" 
    },
    { 
        id: 6, 
        name: "SXSW EDU", 
        date: "2026-03-09", 
        location: "Austin, Texas, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Innovación y creatividad.", 
        lat: 30.2672, 
        lng: -97.7431, 
        website: "https://sxswedu.com/" 
    },
    { 
        id: 7, 
        name: "FETC", 
        date: "2026-01-11", 
        location: "Orlando, Florida, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Alta", 
        notes: "Prioridad B. Marketing Capabilia y Benchlab. Actualizarse en tendencias tecnológicas.", 
        lat: 28.5383, 
        lng: -81.3792, 
        website: "https://www.fetc.org/" 
    },
    { 
        id: 8, 
        name: "TCEA Convention", 
        date: "2026-01-31", 
        location: "San Antonio, Texas, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Networking y scouting.", 
        lat: 29.4241, 
        lng: -98.4936, 
        website: "https://convention.tcea.org/about/faqs/" 
    },
    { 
        id: 9, 
        name: "HolonIQ Global Skills Week", 
        date: "2026-03-24", 
        location: "Washington D.C., EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Reforzar liderazgo en skills.", 
        lat: 38.9072, 
        lng: -77.0369, 
        website: "https://portal.qshesummits.com/event/global-skills-week/home" 
    },
    { 
        id: 10, 
        name: "ATD 2025 Int. Conf. & Expo", 
        date: "2026-05-17", 
        location: "Los Ángeles, California, EE.UU.", 
        region: "Norteamérica", 
        type: "Corporate learning / L&D", 
        relevance: "Alta", 
        notes: "Prioridad B. Dirección Comercial y Marketing. Generación de leads B2B.", 
        lat: 34.0522, 
        lng: -118.2437, 
        website: "https://www.nferias.com/atd-conference-exposition/" 
    },
    { 
        id: 11, 
        name: "DevLearn 2025 Conf. & Expo", 
        date: "Por confirmar (Estimado: Noviembre 2026)", 
        location: "Las Vegas, Nevada, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Corporate Brand. Suele ser en Noviembre.", 
        lat: 36.1699, 
        lng: -115.1398, 
        website: "" 
    },
    { 
        id: 12, 
        name: "OLC Accelerate 2025", 
        date: "Por confirmar (Estimado: Noviembre 2026)", 
        location: "Orlando, Florida, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Fechas exactas aún no publicadas.", 
        lat: 28.5383, 
        lng: -81.3792, 
        website: "" 
    },
    { 
        id: 13, 
        name: "ISTE+ASCD Instructional Leaders", 
        date: "2026-01-16", 
        location: "San Diego, California, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Foco en liderazgo.", 
        lat: 32.7157, 
        lng: -117.1611, 
        website: "https://event.iste-ascd.org/ILS26/" 
    },
    { 
        id: 14, 
        name: "FETC 2026", 
        date: "2026-01-11", 
        location: "Orlando, Florida, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Duplicado de FETC (arriba).", 
        lat: 28.5383, 
        lng: -81.3792, 
        website: "https://www.fetc.org/" 
    },
    { 
        id: 15, 
        name: "SXSW EDU 2026", 
        date: "2026-03-09", 
        location: "Austin, Texas, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Marketing Corporativo. Duplicado de SXSW EDU (arriba).", 
        lat: 30.2672, 
        lng: -97.7431, 
        website: "https://sxswedu.com/" 
    },
    { 
        id: 16, 
        name: "ISTELive 26 + ASCD Annual 26", 
        date: "2026-06-28", 
        location: "Orlando, Florida, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Alta", 
        notes: "Prioridad B. Marketing Capabilia y Benchlab. Fecha confirmada.", 
        lat: 28.5383, 
        lng: -81.3792, 
        website: "https://conference.iste.org/" 
    },
    { 
        id: 17, 
        name: "CIC Presidents Institute 2026", 
        date: "2026-01-04", 
        location: "Orlando, Florida, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Networking presidentes.", 
        lat: 28.5383, 
        lng: -81.3792, 
        website: "https://cic.edu/event/2026-presidents-institute/" 
    },
    { 
        id: 18, 
        name: "AAC&U Annual Meeting 2026", 
        date: "2026-01-21", 
        location: "Washington D.C., EE.UU.", 
        region: "Norteamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Networking y scouting.", 
        lat: 38.9072, 
        lng: -77.0369, 
        website: "https://www.aacu.org/events" 
    },
    { 
        id: 19, 
        name: "ACE Experience 2026", 
        date: "2026-02-25", 
        location: "Washington D.C., EE.UU.", 
        region: "Norteamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Networking y scouting.", 
        lat: 38.9072, 
        lng: -77.0369, 
        website: "https://web.cvent.com/event/7d76e475-73c0-4b97-b034-7cf56b1dd7b9/summary" 
    },
    { 
        id: 20, 
        name: "AI K12 Deeper Learning Summit", 
        date: "2026-02-03", 
        location: "Hershey, PA, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Parte de PETE&C.", 
        lat: 40.2859, 
        lng: -76.6502, 
        website: "https://www.peteandc.org/2026/ThirdSummit.cfm" 
    },
    { 
        id: 21, 
        name: "Beyond School Hours (BSH)", 
        date: "2026-03-01", 
        location: "Orlando, Florida, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Networking y scouting.", 
        lat: 28.5383, 
        lng: -81.3792, 
        website: "https://beyondschoolhours.org/" 
    },
    { 
        id: 22, 
        name: "Digital Learning Annual Conf.", 
        date: "2026-02-18", 
        location: "Sacramento, California, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Fecha confirmada (DLAC Ignite).", 
        lat: 38.5816, 
        lng: -121.4944, 
        website: "https://conference.deelac.com/future-dlac-dates" 
    },
    { 
        id: 23, 
        name: "AASA National Conf. on Education", 
        date: "2026-02-12", 
        location: "Nashville, Tennessee, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Networking y scouting.", 
        lat: 36.1627, 
        lng: -86.7816, 
        website: "https://www.aasa.org/professional-learning/national-conference-on-education" 
    },
    { 
        id: 24, 
        name: "Spring CUE 2025", 
        date: "2026-03-19", 
        location: "Palm Springs, California, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Networking y scouting.", 
        lat: 33.8303, 
        lng: -116.5453, 
        website: "https://cadrek12.org/events/2026/03/19/computer-using-educators-spring-cue-2026-national-conference-palm-springs-ca" 
    },
    { 
        id: 25, 
        name: "UPCEA 2025 Annual Conference", 
        date: "2026-04-15", 
        location: "Nueva Orleans, Louisiana, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Marketing Corporativo. Networking y scouting.", 
        lat: 29.9511, 
        lng: -90.0715, 
        website: "https://conferences.upcea.edu/annual2026/" 
    },
    { 
        id: 26, 
        name: "CoSN 2025", 
        date: "2026-04-13", 
        location: "Chicago, Illinois, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Networking y scouting.", 
        lat: 41.8781, 
        lng: -87.6298, 
        website: "https://serve.uncg.edu/event/cosn-conference-2026/" 
    },
    { 
        id: 27, 
        name: "Digital Credentials Summit", 
        date: "2026-02-18", 
        location: "Filadelfia, Pensilvania, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Credenciales digitales.", 
        lat: 39.9526, 
        lng: -75.1652, 
        website: "https://www.cvent.com/c/abstracts/4eacc00f-fabc-4fae-8a73-72d26b867f39" 
    },
    { 
        id: 28, 
        name: "Graduate Enrollment Mgmt Summit", 
        date: "2026-04-08", 
        location: "Baltimore, Maryland, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Marketing Corporativo. Networking y scouting.", 
        lat: 39.2904, 
        lng: -76.6122, 
        website: "https://nagap.memberclicks.net/2025-GEM-Summit" 
    },
    { 
        id: 29, 
        name: "EDUCAUSE Cybersecurity & Privacy", 
        date: "Por confirmar (Estimado: Mayo 2026)", 
        location: "Por confirmar", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Marketing Corporativo. Sin anuncio oficial 2026.", 
        lat: 39.7392, 
        lng: -104.9903, 
        website: "" 
    },
    { 
        id: 30, 
        name: "Model Schools Conference 2025", 
        date: "2026-06-28", 
        location: "Orlando, Florida, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Fecha confirmada.", 
        lat: 28.5383, 
        lng: -81.3792, 
        website: "https://www.hmhco.com/model-schools-conference" 
    },
    { 
        id: 31, 
        name: "Get Your Teach On (GYTO) Fest", 
        date: "2026-01-17", 
        location: "Las Vegas, Nevada, EE.UU.", 
        region: "Norteamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Capabilia y Benchlab. Fecha confirmada.", 
        lat: 36.1699, 
        lng: -115.1398, 
        website: "https://events.getyourteachon.com/vegas2026?ref=gytosite" 
    },
    { 
        id: 32, 
        name: "InstructureCon 2025", 
        date: "2026-07-21", 
        location: "Louisville, Kentucky, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Fecha confirmada.", 
        lat: 38.2527, 
        lng: -85.7585, 
        website: "https://www.instructure.com/events/instructurecon/faqs" 
    },
    { 
        id: 33, 
        name: "Inbound HubSpot", 
        date: "2026-09-16", 
        location: "Boston, Massachusetts, EE.UU.", 
        region: "Norteamérica", 
        type: "Marketing y tecnología comercial", 
        relevance: "Media", 
        notes: "Prioridad C. Marketing Corporativo y Benchlab/Klarway. Adopción de buenas prácticas comerciales.", 
        lat: 42.3601, 
        lng: -71.0589, 
        website: "https://www.cmswire.com/events/conference/hubspot-inbound-boston-2026/" 
    },
    { 
        id: 34, 
        name: "Learning Leaders Conference", 
        date: "2026-11-02", 
        location: "Las Vegas, Nevada, EE.UU.", 
        region: "Norteamérica", 
        type: "Corporate learning / L&D", 
        relevance: "Media", 
        notes: "Prioridad C. Dirección Comercial y Marketing. Networking y scouting.", 
        lat: 36.1699, 
        lng: -115.1398, 
        website: "https://www.learningguild.com/event/learning-leadership-conference" 
    },
    { 
        id: 35, 
        name: "NACAC Conference 2026", 
        date: "2026-10-08", 
        location: "Minneapolis, Minnesota, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Networking y scouting.", 
        lat: 44.9778, 
        lng: -93.2650, 
        website: "https://www.tacac.org/nacac" 
    },
    { 
        id: 36, 
        name: "EDUCAUSE Annual Conf. 2026", 
        date: "2026-09-29", 
        location: "Denver, Colorado, EE.UU.", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Fecha confirmada.", 
        lat: 39.7392, 
        lng: -104.9903, 
        website: "https://events.educause.edu/annual-conference/2026" 
    },
    { 
        id: 37, 
        name: "IFE EdTech Summit", 
        date: "2026-01-27", 
        location: "Monterrey, México", 
        region: "Latinoamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Muy Alta", 
        notes: "Prioridad A. Marketing Capabilia y Benchlab. Stand de grupo sugerido.", 
        lat: 25.6866, 
        lng: -100.3161, 
        website: "https://startupslatam.com/ife-edtech-summit-2026-monterrey-sera-el-epicentro-de-la-innovacion-educativa-en-america-latina/" 
    },
    { 
        id: 38, 
        name: "Bett Brasil", 
        date: "2026-05-05", 
        location: "São Paulo, Brasil", 
        region: "Latinoamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Muy Alta", 
        notes: "Prioridad A. Marketing Capabilia y Benchlab. Stand de grupo sugerido.", 
        lat: -23.5505, 
        lng: -46.6333, 
        website: "https://brasil.bettshow.com/credenciamento" 
    },
    { 
        id: 39, 
        name: "Edutechnia", 
        date: "2026-08-26", 
        location: "Bogotá, Colombia", 
        region: "Latinoamérica", 
        type: "Tecnología educativa / K-12 / EdTech", 
        relevance: "Alta", 
        notes: "Prioridad B. Marketing Capabilia y Benchlab. Principal evento en región Andina.", 
        lat: 4.7110, 
        lng: -74.0721, 
        website: "https://www.edutechnia.com/pdf/Presentacion-Edutechnia-2026.pdf" 
    },
    { 
        id: 40, 
        name: "EdTech Conference Buenos Aires", 
        date: "Por confirmar", 
        location: "Buenos Aires, Argentina", 
        region: "Latinoamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Sin información oficial 2026.", 
        lat: -34.6037, 
        lng: -58.3816, 
        website: "" 
    },
    { 
        id: 41, 
        name: "Edutic Ontour", 
        date: "2026-03-18", 
        location: "Ciudad de México, México", 
        region: "Latinoamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Conf. para CDMX.", 
        lat: 19.4326, 
        lng: -99.1332, 
        website: "https://conference.edutic.org/mx/cdmx2026/" 
    },
    { 
        id: 42, 
        name: "HolonIQ Impact Week", 
        date: "2026-09-08", 
        location: "Nueva York / Singapur", 
        region: "Norteamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Fecha confirmada.", 
        lat: 40.7128, 
        lng: -74.0060, 
        website: "https://impactweek.com/" 
    },
    { 
        id: 43, 
        name: "THE Latin America Univ. Summit", 
        date: "2026-05-12", 
        location: "Barranquilla, Colombia", 
        region: "Latinoamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Muy Alta", 
        notes: "Prioridad A. Estrategia y Corporate Brand. Stand de grupo sugerido.", 
        lat: 10.9685, 
        lng: -74.7813, 
        website: "https://www.timeshighered-events.com/latin-america-universities-summit-2026" 
    },
    { 
        id: 44, 
        name: "Programa: Educ. Superior (Medellín)", 
        date: "Por confirmar", 
        location: "Medellín, Colombia", 
        region: "Latinoamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Evento específico.", 
        lat: 6.2442, 
        lng: -75.5812, 
        website: "" 
    },
    { 
        id: 45, 
        name: "Programa: Educ. Superior (Lima)", 
        date: "Por confirmar", 
        location: "Lima, Perú", 
        region: "Latinoamérica", 
        type: "Educación / innovación (general)", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Corporate Brand. Evento específico.", 
        lat: -12.0464, 
        lng: -77.0428, 
        website: "" 
    },
    { 
        id: 46, 
        name: "Etech Evolving Education", 
        date: "Por confirmar", 
        location: "Puebla, México", 
        region: "Latinoamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Marketing Corporativo. Sin anuncio oficial 2026.", 
        lat: 19.0414, 
        lng: -98.2063, 
        website: "" 
    },
    { 
        id: 47, 
        name: "CAEI Congreso de las Américas", 
        date: "Por confirmar (Bianual)", 
        location: "Por confirmar", 
        region: "Latinoamérica", 
        type: "Educación superior / internacionalización", 
        relevance: "Media", 
        notes: "Prioridad C. Relaciones Internacionales. Probablemente 2027.", 
        lat: 9.9281, 
        lng: -84.0907, 
        website: "" 
    },
    { 
        id: 48, 
        name: "QS Higher Ed Summit: Americas 25", 
        date: "2026-10-01", 
        location: "Guadalajara, México", 
        region: "Latinoamérica", 
        type: "Educación superior / internacionalización", 
        relevance: "Alta", 
        notes: "Prioridad B. Relaciones Internacionales. Fecha confirmada (Edición 2026).", 
        lat: 20.6597, 
        lng: -103.3496, 
        website: "https://www.qs.com/conferences/americas" 
    },
    { 
        id: 49, 
        name: "QS Higher Ed Summit: Americas 26", 
        date: "2026-10-01", 
        location: "Guadalajara, México", 
        region: "Latinoamérica", 
        type: "Educación superior / internacionalización", 
        relevance: "Alta", 
        notes: "Prioridad B. Relaciones Internacionales. Duplicado de arriba.", 
        lat: 20.6597, 
        lng: -103.3496, 
        website: "https://www.qs.com/conferences/americas" 
    },
    { 
        id: 50, 
        name: "Innova Educa", 
        date: "Por confirmar (Estimado: Noviembre 2026)", 
        location: "Buenos Aires, Argentina", 
        region: "Latinoamérica", 
        type: "Educación digital / innovación educativa", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Marketing Corporativo. Sin anuncio oficial 2026.", 
        lat: -34.6037, 
        lng: -58.3816, 
        website: "" 
    },
    { 
        id: 51, 
        name: "UNIVERSIA", 
        date: "No programado", 
        location: "N/A", 
        region: "Latinoamérica", 
        type: "Educación superior / internacionalización", 
        relevance: "Alta", 
        notes: "Prioridad B. Relaciones Internacionales. Evento trienal/quinquenal.", 
        lat: -15.0000, 
        lng: -60.0000, 
        website: "" 
    },
    { 
        id: 52, 
        name: "FORUMEDUCA", 
        date: "Por confirmar (Estimado: Marzo 2026)", 
        location: "España", 
        region: "España", 
        type: "Educación digital / innovación educativa", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Marketing Corporativo. Sin anuncio oficial.", 
        lat: 40.4168, 
        lng: -3.7038, 
        website: "" 
    },
    { 
        id: 53, 
        name: "Global Education Forum - Madrid", 
        date: "2026-01-15", 
        location: "Madrid, España", 
        region: "España", 
        type: "Educación superior / internacionalización", 
        relevance: "Media", 
        notes: "Prioridad C. Relaciones Internacionales. Posible coincidencia Youth Global Forum.", 
        lat: 40.4168, 
        lng: -3.7038, 
        website: "https://thecgdl.org/ygf2026/" 
    },
    { 
        id: 54, 
        name: "EnlightED", 
        date: "Por confirmar (Estimado: Oct/Nov 2026)", 
        location: "Madrid, España", 
        region: "España", 
        type: "Educación digital / innovación educativa", 
        relevance: "Alta", 
        notes: "Prioridad B. Estrategia y Marketing Corporativo. Sin anuncio oficial.", 
        lat: 40.4168, 
        lng: -3.7038, 
        website: "" 
    },
    { 
        id: 55, 
        name: "OLC Innovate 2026", 
        date: "2026-03-03", 
        location: "Virtual", 
        region: "Virtual/Global", 
        type: "Educación digital / innovación educativa", 
        relevance: "Media", 
        notes: "Prioridad C. Estrategia y Marketing Corporativo. Fecha confirmada.", 
        lat: 0, 
        lng: 0, 
        website: "https://onlinelearningconsortium.org/conferences/" 
    },
    { 
        id: 56, 
        name: "World Education Summit", 
        date: "2026-02-04", 
        location: "Dubai, EAU", 
        region: "Virtual/Global", 
        type: "Educación superior / internacionalización", 
        relevance: "Media", 
        notes: "Prioridad C. Relaciones Internacionales. Fecha confirmada (Elets).", 
        lat: 25.2048, 
        lng: 55.2708, 
        website: "https://educationsummit.com/" 
    },
    {
        id: 57,
        name: "Inn.kind FIEd 2026",
        date: "2026-05-19",
        location: "Por confirmar",
        region: "Latinoamérica",
        type: "Educación / innovación (general)",
        relevance: "Media",
        notes: "19 al 21 de mayo",
        lat: -15.0000,
        lng: -60.0000,
        website: "https://innkind.com/"
    },
    {
        id: 58,
        name: "Realcup",
        date: "2026-11-11",
        location: "Por confirmar",
        region: "Latinoamérica",
        type: "Educación superior / internacionalización",
        relevance: "Media",
        notes: "11 al 13 de noviembre",
        lat: -15.0000,
        lng: -60.0000,
        website: "https://realcup.org/"
    },
    {
        id: 59,
        name: "RECLA",
        date: "2026-05-27",
        location: "Por confirmar",
        region: "Latinoamérica",
        type: "Educación superior / internacionalización",
        relevance: "Media",
        notes: "27, 28 y 29 de mayo",
        lat: -15.0000,
        lng: -60.0000,
        website: "https://recla.org/encuentro-regional/"
    }
];
